name: "plata_risk"
version: "1.0.0"
config-version: 2

profile: "plata_risk"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

models:
  plata_risk:
    staging:
      +materialized: view
    marts:
      +materialized: table
